[package]
name = "xtask"
version = "0.1.0"
authors = ["Jakub Trąd <jakubtrad@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
log = "0.4.8"
pretty_env_logger = "0.4.0"
dotenv = "0.15.0"
cmd_lib = "0.7.8"
